# Generated by Django 6.0.2 on 2026-02-08 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='movie/images/'),
        ),
        migrations.AddField(
            model_name='movie',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
